dataset_name: Folktables_CA_2018_Public_Coverage
bootstrap_fraction: 0.8
n_estimators: 200
computation_mode: error_analysis
num_runs: 1
runs_seed_lst: [100]
sensitive_attributes_dct: {'SEX': '2', 'RAC1P': ['2', '3', '4', '5', '6', '7', '8', '9'], 'SEX & RAC1P': None}